### ISSUE TITLE
How to ues outline

### ISSUE THREAD

**Issue by XuJianxing** [awesome-vpn/awesome-vpn#41]
如何获取密钥

**Comment by hugetiny** [comment]
ss服务器专属的订阅链接已经放在首页，直接复制粘贴，不过目前outline不支持订阅链接和批量添加，我正在尝试开发一个优化版

**Comment by XuJianxing** [comment]
outline客户端需要添加访问密钥才能添加服务器，不知道这个访问密钥应该如何获取

**Comment by hugetiny** [comment]
> outline客户端需要添加访问密钥才能添加服务器，不知道这个访问密钥应该如何获取

访问密钥就是SS链接
